export const MSSQL_USER = "MSSQL_USER";
export const MSSQL_PASSWORD = "MSSQL_PASSWORD";
export const MSSQL_ADDRESS = "MSSQL_ADDRESS";
export const MSSQL_DATABASE = "MSSQL_DATABASE";
export const SERVICE_ACCOUNT = "SERVICE_ACCOUNT";
export const FUNC_REGION = "FUNC_REGION";
export const XLS_CONTENT_TYPE = "XLS_CONTENT_TYPE";
export const BUCKET_ID = "BUCKET_ID";
